name: Exercises
version: 1.0.0.0

dependencies:
  - base >= 4.7 && < 5

library:
  default-extensions:
    - GHC2021
  source-dirs: src
  ghc-options:
    - -O
    - -rtsopts
    - -threaded
    - -W
    - -Werror
    - -with-rtsopts=-N

tests:
  Exercises-test:
    main: TestMain.hs
    source-dirs: test
    ghc-options:
      - -O
      - -rtsopts
      - -threaded
      - -W
      - -Werror
      - -with-rtsopts=-N
    dependencies:
      - Exercises
      - tasty
      - tasty-discover
      - tasty-hunit
