name: Haskell
version: 1.0.0.0

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  Haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Haskell
      - tasty
      - tasty-discover
      - tasty-hunit
