name: Exercises
version: 1.0.0.0
language: GHC2021

dependencies:
  - base >= 4.7 && < 5

library:
  ghc-options:
    - -O
    - -W
    - -Werror
  source-dirs: src

tests:
  Exercises-test:
    ghc-options:
      - -O
      - -rtsopts
      - -threaded
      - -W
      - -Werror
      - -with-rtsopts=-N
    dependencies:
      - Exercises
      - tasty
      - tasty-discover
      - tasty-hunit
    main: TestMain.hs
    source-dirs: test
