{-# LANGUAGE NoImplicitPrelude #-}

module Base.Prelude
  -- (
  --   all,
  --   and,
  --   any,
  --   -- break,
  --   compare,
  --   -- concat,
  --   -- concatMap,
  --   const,
  --   curry,
  --   cycle,
  --   drop,
  --   dropWhile,
  --   either,
  --   elem,
  --   -- error,
  --   even,
  --   filter,
  --   flip,
  --   foldl,
  --   foldl1,
  --   -- foldMap,
  --   foldr,
  --   foldr1,
  --   fst,
  --   -- gcd,
  --   getLine,
  --   head,
  --   id,
  --   init,
  --   -- iterate,
  --   last,
  --   length,
  --   -- lines,
  --   -- lookup,
  --   map,
  --   max,
  --   maximum,
  --   min,
  --   minimum,
  --   not,
  --   -- notElem,
  --   null,
  --   odd,
  --   or,
  --   otherwise,
  --   print,
  --   product,
  --   putStr,
  --   putStrLn,
  --   repeat,
  --   replicate,
  --   reverse,
  --   scanl,
  --   scanl1,
  --   scanr,
  --   scanr1,
  --   snd,
  --   -- span,
  --   -- splitAt,
  --   subtract,
  --   sum,
  --   tail,
  --   take,
  --   takeWhile,
  --   uncurry,
  --   -- unlines,
  --   -- unwords,
  --   unzip,
  --   unzip3,
  --   -- words,
  --   zip,
  --   zip3,
  --   zipWith,
  --   zipWith3
  -- )
where

import Base.Data.Bool
import Base.Prelude.Base
import Base.Prelude.Either
import Base.Prelude.Foldable
import Base.Prelude.IO
import Base.Prelude.List
import Base.Prelude.Maybe
import Base.Prelude.Num
import Base.Prelude.Tuple