name: Test exercises

on:
  workflow_dispatch:

jobs:
  haskell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      name: Add Stack binaries to PATH

    - uses: actions/cache@v3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: haskell-${{ runner.os }}

    - run: cd Exercises && stack test
